import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: {
    padding: 16,
    paddingBottom: 96,
    gap: 14,
  },
  topArea: {
    gap: 14,
  },
  hero: {
    minHeight: 46,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  heroTitle: {
    marginTop: 2,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '900',
    textAlign: 'center',
  },
  heroSubtitle: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    maxWidth: 330,
  },
  shortcutGrid: {
    flexDirection: 'row',
    gap: 9,
  },
  shortcutCard: {
    flex: 1,
    minHeight: 92,
    borderRadius: 20,
    borderWidth: 1,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  shortcutIcon: {
    width: 36,
    height: 36,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 2,
  },
  shortcutTitle: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  shortcutSubtitle: {
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyMeCard: {
    padding: 18,
    gap: 14,
    alignItems: 'center',
  },
  emptyIcon: {
    width: 52,
    height: 52,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTextBlock: {
    gap: 4,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptySubtitle: {
    maxWidth: 320,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  meCard: {
    padding: 16,
    gap: 14,
  },
  meHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  meHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  sectionEyebrow: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
  },
  meTitle: {
    marginTop: 1,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '900',
  },
  meSubtitle: {
    marginTop: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 15,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingRow: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  ttrOverview: {
    flexDirection: 'row',
    gap: 10,
  },
  primaryTtrTile: {
    flex: 1.45,
    minHeight: 108,
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    justifyContent: 'center',
  },
  primaryTtrLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
  },
  primaryTtrValue: {
    marginTop: 4,
    fontSize: 38,
    lineHeight: 44,
    fontWeight: '900',
  },
  secondaryStats: {
    flex: 1,
    gap: 5,
  },
  miniStat: {
    flex: 1,
    minHeight: 45,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  miniStatLabel: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.2,
  },
  miniStatValue: {
    marginTop: 2,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
  },
  historyHeader: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  historyTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
  },
  historyLink: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  recentList: {
    gap: 8,
  },
  recentRow: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  recentMain: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  recentTitle: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  recentMeta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  recentScore: {
    alignItems: 'flex-end',
    minWidth: 48,
  },
  recentTtr: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '900',
  },
  recentDelta: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '900',
  },
  clubCard: {
    padding: 16,
    gap: 14,
  },
  clubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  clubHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  clubTitle: {
    marginTop: 1,
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '900',
  },
  clubSubtitle: {
    marginTop: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
  },
  clubLoadingBox: {
    minHeight: 84,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  clubMessageBox: {
    gap: 12,
  },
  clubMatchList: {
    gap: 8,
  },
  clubMatchRow: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 11,
    gap: 9,
  },
  clubMatchTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  clubMatchMeta: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  clubMatchMetaText: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  completedPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  completedPillText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.25,
  },
  clubMatchScoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  clubMatchTeam: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  clubMatchAwayTeam: {
    textAlign: 'right',
  },
  clubScoreBox: {
    minWidth: 64,
    minHeight: 34,
    borderRadius: 13,
    borderWidth: 1,
    paddingHorizontal: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  clubScoreText: {
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '900',
  },
  clubScoreDivider: {
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
  },
  clubMatchFooter: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  homeBody: {
    fontSize: 14,
    lineHeight: 21,
  },
});
