import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    content: {
        padding: 16,
        paddingTop: 20,
        paddingBottom: 112,
        gap: 16,
    },
    headerRow: {
        minHeight: 42,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
    },
    backButton: {
        width: 38,
        height: 38,
        borderRadius: 19,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    profileTitleBlock: {
        marginTop: -6,
        gap: 2,
    },
    headerText: {
        flex: 1,
    },
    title: {
        fontSize: 25,
        lineHeight: 32,
        fontWeight: '900',
    },
    subtitle: {
        marginTop: 2,
        fontSize: 14,
        lineHeight: 20,
    },
    infoCard: {
        padding: 16,
        gap: 10,
    },
    badgeRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    infoRow: {
        minHeight: 42,
        paddingVertical: 9,
        borderBottomWidth: StyleSheet.hairlineWidth,
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    infoLabel: {
        fontSize: 14,
        lineHeight: 20,
    },
    infoValue: {
        flex: 1,
        textAlign: 'right',
        fontSize: 14,
        lineHeight: 20,
        fontWeight: '800',
    },
    filterCard: {
        padding: 14,
        gap: 12,
    },
    filterHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    filterTitle: {
        fontSize: 16,
        lineHeight: 22,
        fontWeight: '900',
    },
    filterSubtitle: {
        marginTop: 2,
        fontSize: 12,
        lineHeight: 17,
    },
    filterRow: {
        flexDirection: 'row',
        gap: 10,
    },
    dateInputBlock: {
        flex: 1,
        gap: 6,
    },
    inputLabel: {
        fontSize: 12,
        lineHeight: 16,
        fontWeight: '800',
    },
    dateInput: {
        height: 42,
        borderWidth: 1,
        borderRadius: 14,
        paddingHorizontal: 12,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: '800',
    },
    filterButtonRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
    },
    resetButton: {
        minHeight: 40,
        borderRadius: 14,
        borderWidth: 1,
        paddingHorizontal: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    resetButtonText: {
        fontSize: 13,
        lineHeight: 18,
        fontWeight: '900',
    },
    applyButton: {
        minHeight: 40,
        borderRadius: 14,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    applyButtonText: {
        color: '#fff',
        fontSize: 13,
        lineHeight: 18,
        fontWeight: '900',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    sectionTitle: {
        fontSize: 20,
        lineHeight: 26,
        fontWeight: '900',
    },
    sectionSubtitle: {
        marginTop: 2,
        fontSize: 13,
        lineHeight: 18,
    },
    loader: {
        paddingVertical: 24,
    },
    inlineLoader: {
        paddingVertical: 12,
    },
    error: {
        fontSize: 14,
        lineHeight: 20,
    },
    stack: {
        gap: 12,
    },
    teamCard: {
        padding: 14,
        gap: 12,
    },
    teamTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    teamIcon: {
        width: 42,
        height: 42,
        borderRadius: 15,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    teamText: {
        flex: 1,
        minWidth: 0,
    },
    teamName: {
        fontSize: 16,
        lineHeight: 22,
        fontWeight: '900',
    },
    teamLeague: {
        marginTop: 2,
        fontSize: 13,
        lineHeight: 18,
    },
    playerCard: {
        borderWidth: 1,
        borderRadius: 24,
        padding: 14,
        gap: 12,
    },
    playerCardPressed: {
        opacity: 0.78,
        transform: [{ scale: 0.992 }],
    },
    playerTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    playerRankBadge: {
        width: 38,
        height: 38,
        borderRadius: 999,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    playerRankText: {
        fontSize: 14,
        lineHeight: 18,
        fontWeight: '900',
    },
    playerText: {
        flex: 1,
        minWidth: 0,
    },
    playerName: {
        fontSize: 16,
        lineHeight: 22,
        fontWeight: '900',
    },
    playerMeta: {
        marginTop: 2,
        fontSize: 13,
        lineHeight: 18,
    },
    scheduleDayCard: {
        padding: 14,
        gap: 12,
    },
    scheduleDayHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    scheduleDayIcon: {
        width: 38,
        height: 38,
        borderRadius: 14,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    scheduleDayTitleBlock: {
        flex: 1,
        minWidth: 0,
    },
    scheduleDayTitle: {
        fontSize: 17,
        lineHeight: 23,
        fontWeight: '900',
    },
    scheduleDaySubtitle: {
        marginTop: 1,
        fontSize: 12,
        lineHeight: 17,
    },
    matchCard: {
        padding: 14,
        gap: 11,
    },
    matchTopMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    matchScoreRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 9,
    },
    matchTeam: {
        flex: 1,
        fontSize: 14,
        lineHeight: 19,
        fontWeight: '900',
    },
    awayTeam: {
        textAlign: 'right',
    },
    scoreBox: {
        minWidth: 76,
        minHeight: 38,
        borderRadius: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 5,
        paddingHorizontal: 8,
    },
    scoreText: {
        fontSize: 21,
        lineHeight: 27,
        fontWeight: '900',
    },
    scoreDivider: {
        fontSize: 18,
        lineHeight: 24,
    },
    vsBox: {
        minWidth: 54,
        minHeight: 34,
        borderRadius: 14,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    vsText: {
        fontSize: 11,
        lineHeight: 15,
        fontWeight: '900',
        letterSpacing: 0.5,
    },
    matchMetaRow: {
        gap: 5,
    },
    metaLine: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        flexShrink: 1,
    },
    metaText: {
        flexShrink: 1,
        fontSize: 13,
        lineHeight: 18,
    },
    headerActionButton: {
        width: 38,
        height: 38,
        borderRadius: 19,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dateButton: {
        height: 42,
        borderWidth: 1,
        borderRadius: 14,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    dateButtonText: {
        flex: 1,
        fontSize: 14,
        lineHeight: 20,
        fontWeight: '800',
    },
    calendarOverlay: {
        flex: 1,
        padding: 18,
        backgroundColor: 'rgba(0, 0, 0, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarSheet: {
        width: '100%',
        maxWidth: 390,
        borderRadius: 28,
        borderWidth: 1,
        padding: 16,
        gap: 16,
    },
    calendarTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    calendarTitle: {
        fontSize: 18,
        lineHeight: 24,
        fontWeight: '900',
    },
    calendarSubtitle: {
        marginTop: 2,
        fontSize: 13,
        lineHeight: 18,
    },
    calendarCloseButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarMonthRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 12,
    },
    calendarNavButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: StyleSheet.hairlineWidth,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarMonthText: {
        flex: 1,
        textAlign: 'center',
        fontSize: 15,
        lineHeight: 21,
        fontWeight: '900',
        textTransform: 'capitalize',
    },
    weekdayRow: {
        flexDirection: 'row',
    },
    weekdayText: {
        flex: 1,
        textAlign: 'center',
        fontSize: 12,
        lineHeight: 16,
        fontWeight: '900',
    },
    calendarGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        rowGap: 6,
    },
    calendarDaySlot: {
        width: `${100 / 7}%`,
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarDayButton: {
        borderRadius: 14,
        borderWidth: 1,
    },
    calendarDayText: {
        fontSize: 14,
        lineHeight: 19,
        fontWeight: '900',
    },
    calendarFooter: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
    },
    calendarClearButton: {
        minHeight: 40,
        borderRadius: 14,
        borderWidth: 1,
        paddingHorizontal: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarClearButtonText: {
        fontSize: 13,
        lineHeight: 18,
        fontWeight: '900',
    },
    calendarTodayButton: {
        minHeight: 40,
        borderRadius: 14,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarTodayButtonText: {
        color: '#fff',
        fontSize: 13,
        lineHeight: 18,
        fontWeight: '900',
    },
});
